// This file is autogenerated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore} from 'firebase/firestore';

// Your web app's Firebase configuration
const firebaseConfig = {
  projectId: "gymlogin-pro",
  appId: "1:1025011579347:web:275833ca7bffe7271dd726",
  storageBucket: "gymlogin-pro.firebasestorage.app",
  apiKey: "AIzaSyBON5_tW9SuFrIgaOO-uJQML6VqP3GgIKI",
  authDomain: "gymlogin-pro.firebaseapp.com",
  messagingSenderId: "1025011579347"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export {app, db};